version: "3.9"

services:
  rss-morning:
    command: >
      --config configs/config.toml
      --log-level INFO
    environment:
      TYPESAFE_API_KEY: ""
      OPENROUTER_API_KEY: ""
      RESEND_API_KEY: ""
      RESEND_FROM_EMAIL: "no-reply@example.com"
